### PR TITLE
Fix issue #13: https://github.com/opensearch-project/opensearch-oci-o…

### LINKED ISSUE #13: [BUG] node_disconnected_exception when trying to configure oci repository
### What is the bug?
_A clear and concise description of the bug._
node_disconnected_exception when trying to configure oci repository

### How can one reproduce the bug?
_Steps to reproduce the behavior._
I am trying to configure the repository with Instance Principal for OCI ObjectStorage plugin as defined in https://github.com/opensearch-project/opensearch-oci-object-storage. But when I try to configure with this command, I always get an error -
[opensearch@opensearch-es-data-0 ~]$ curl -XPUT "http://localhost:9200/_snapshot/oci_repository
" -H 'Content-Type: application/json' -d"
> {
> \"type\": \"oci\",
> \"settings\":

{ > \"client\": \"default\", > \"endpoint\": \"[https://objectstorage.us-ashburn-1.oraclecloud.com|https://objectstorage.us-ashburn-1.oraclecloud.com/] \", > \"bucket\": \"opensearch_backup\", > \"namespace\": \"-------\", > \"bucket_compartment_id\": \"NOT ACTUAL\", > \"useInstancePrincipal\": true, > \"forceBucketCreation\" : true > }
> }
> "

{"error":{"root_cause":[

{"type":"node_disconnected_exception","reason":"[opensearch-es-master-2][10.244.6.59:9300][cluster:admin/repository/put] disconnected"}
],"type":"master_not_discovered_exception","reason":"NodeDisconnectedException[[opensearch-es-master-2][10.244.6.59:9300][cluster:admin/repository/put] disconnected]","caused_by":{"type":"node_disconnected_exception","reason":"[opensearch-es-master-2][10.244.6.59:9300][cluster:admin/repository/put] disconnected"}},"status":503}
 
Cluster seems to be in healthy state before the above call -
curl -v -X GET
http://localhost:9200/_cluster/health?pretty

About to connect() to localhost port 9200 (#0)
Trying ::1...
Connected to localhost (::1) port 9200 (#0)
> GET /_cluster/health?pretty HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9200
> Accept: /
>
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 502
< { "cluster_name" : "opensearch-tracking", "status" : "green", "timed_out" : false, "number_of_nodes" : 6, "number_of_data_nodes" : 3, "discovered_master" : true, "active_primary_shards" : 0, "active_shards" : 0, "relocating_shards" : 0, "initializing_shards" : 0, "unassigned_shards" : 0, "delayed_unassigned_shards" : 0, "number_of_pending_tasks" : 0, "number_of_in_flight_fetch" : 0, "task_max_waiting_in_queue_millis" : 0, "active_shards_percent_as_number" : 100.0 }
 
### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

### PR DESCRIPTION
**Pull request by plemouel1**
…bject-storage/issues/13

### Description
This commit addresses issue #13 
See issue #13 for details regarding the encountered problem.

This commit also include sl4j-simple as a dependency so that we can get logging statements from the OCI SDK to show up in OpenSearch logs

### Issues Resolved
#13 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by samuel-oci** [comment]
Hi @plemouel1 , thank you for contribution, I understand the need to disable the security manager to get things working until we can get the policy file to behave the way we would like.
Can you please make the DCO checks to work?

**Comment by plemouel1** [comment]
DCO should be fixed now.

**Comment by plemouel1** [comment]
@samuel-oci Looks like now there isn't anything more for me to do. Can you have a look? Thanks

**Comment by saratvemulapalli** [comment]
@plemouel1 I am sad that we are disabling JSM but if thats something which gets us unblocked Im ok with it. 
Could you open an issue/bug to restore JSM?

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
Will wait for @samuel-oci's ack to merge.

**Review by samuel-oci — APPROVED** [review]

**Pull request merged**
