### PR TITLE
Update main to 3.0.0 baseline

### PR DESCRIPTION
**Pull request by reta**
### Description
Update main to 3.0.0 baseline

### Issues Resolved
N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@andrross could you please help me with this one? thank you!

**Review by andrross — APPROVED** [review]
This looks good to me.

FYI @samuel-oci this will be an impactful change if 2.x distributions are currently being built from the main branch.

**Comment by reta** [comment]
Many apologies @andrross , may I ask you please to retry the failing check one more time :( ? thank you!

**Comment by reta** [comment]
Let's merge it? :-) Thanks!

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
> Let's merge it? :-) Thanks!

@samuel-oci any concerns?

**Pull request merged**
